version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
